from . import (alive, awesome_free_chatgpt, b23tv, bili, bing, blocky, cfstyle,
               chinacovid19, chinaip, clash, dir, dxx, exec_with_return,
               fake_strings, freenom, getfirefox, getkis, gist, github, hash,
               hitokoto, hmcl, keybase, kizunaai, license, lzma, mc, pi,
               randerr, rustdesk, strange_url, thispersondoesnotexist, totp,
               ungoogled_chromium_windows, verceldetect)

__all__ = [
    "bili",
    "bing",
    "freenom",
    "github",
    "kizunaai",
    "mc",
    "pi",
    "strange_url",
    "cfstyle",
    "randerr",
    "verceldetect",
    "totp",
    "exec_with_return",
    "hash",
    "chinaip",
    "keybase",
    "dir",
    "lzma",
    "dxx",
    "gist",
    "getfirefox",
    "getkis",
    "ungoogled_chromium_windows",
    "clash",
    "fake_strings",
    "hmcl",
    "chinacovid19",
    "rustdesk",
    "alive",
    "license",
    "hitokoto",
    "thispersondoesnotexist",
    "awesome_free_chatgpt",
    "blocky",
    "b23tv",
]


def hello():
    print("Hello, world!")
